### PR TITLE
Specific lua code for EDO option

### PR DESCRIPTION
**Pull request by chamalo90**

### CODE REVIEW

**Comment by oliviertilmans** [comment]
Could you:
- Rename the option type to something shorter (à-la TCPTFO)
- Fix the doc tags (some still refer to TCPOption.newedo etc) -- install ldoc (lua-ldoc on debian) and run ldoc. (then check the output in doc/html)
- Fix the indentation

Thanks!

**Comment by chamalo90** [comment]
Updated. An update of pellegre/libcrafter module due to https://github.com/pellegre/libcrafter/pull/40 is needed.
I still have two question :
- Is that possible to declare two modules (ldoc) in a single file ? (for EDO, I had to name the 'new' function for EDOREQUEST 'newr' cause of that issue.
- Which files were badly indented ?

**Comment by oliviertilmans** [comment]
You actually didn't need to rename the cpp classes, just change the way the class is exposed to lua (see lua_init.cpp).

You can document multiple class in one file:
@module TCPExtentededDataOtion
[...]
@type TCPEDORequest
[...]
@type TCPEDO

**Comment by chamalo90** [comment]
Done.

**Comment by oliviertilmans** [comment]
Thanks!

**Pull request merged**
