### PR TITLE
lua: Added support for IPv6 SRH

### PR DESCRIPTION
**Pull request by oliviertilmans**

### CODE REVIEW

**Comment by gdetal** [comment]
@oliviertilmans thanks for the nice work. However, the tests have failed (see https://travis-ci.org/tracebox/tracebox/builds/50961017). Can you check whether this is a behavior introduced by this new version of libcrafter ?

**Comment by oliviertilmans** [comment]
NAT test is failing (last one in the pack), I'll bissect.

**Comment by oliviertilmans** [comment]
Will be fixed by https://github.com/pellegre/libcrafter/pull/17 (was corrupting bitsfield exactly aligned on byte boundaries)

**Comment by oliviertilmans** [comment]
Should be fixed now.

**Comment by oliviertilmans** [comment]
```
iptables v1.4.12: can't initialize iptables table `filter': Permission denied (you must be root)

Perhaps iptables or your kernel needs to be upgraded.

/usr/bin/fakeroot: line 181: 3467 Segmentation fault FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$LIB" "$@"

FAIL: labs/NAT.sh
```
Can't reproduce that error here...

**Comment by gdetal** [comment]
Same on my computer, I'll investigate...

In the mean time can you merge your last 2 commits ?

**Comment by gdetal** [comment]
The master branch does not seem to have this issue on travis see https://travis-ci.org/tracebox/tracebox/builds/24625077 (I've rebuilt it)

**Pull request merged**
