### PR TITLE
Capturing packets transfered and store them on a server using pcap lib.

### PR DESCRIPTION
**Pull request by chamalo90**
Sync done using cURL api & -c (capture option) followed by an upload url.
Timeout for sending trace : 8 seconds
Current server opened for testing : 
$tracebox uclouvain.be -c http://ns328523.ip-37-187-114.eu:3000/curl

### CODE REVIEW

**Comment by oliviertilmans** [comment]
Hello, could you:
- add one extra option to specify the name of the pcap file (before defaulting to /tmp/capture.pcap), e.g. 'f'
- Remove the deletion of the capture file on exit

**Comment by chamalo90** [comment]
Hello,
I updated my commit to be compliant with your remarks.

**Comment by chamalo90** [comment]
Security issue related to the server has been fixed.
Now, all GET requests are redirected to home page (which default RoR one, for now).

**Comment by oliviertilmans** [comment]
Merged, thanks.

**Pull request merged**
